<!DOCTYPE html>
<html lang="de">
<head>
	<title><?php echo $this->getConf('system_title') ?> :: <?php echo $this->title ?></title>
	<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
	
	<!-- include css -->
	<?php foreach ($this->arrCssFiles as $css) { ?>
	<link rel="stylesheet" type="text/css" href="css<?php echo $css ?>" media="screen" />
	<?php } ?>
	<!-- include css -->
	
</head>
<body>
	<?php include $inc; ?>	
</body>
</html>
