<?php 
/**
 * template Seite 1 zum editieren des E- Berichtes
 */
$B = $this->view['data'];
//$this->tools->debug($B->_data);
?>
<div id="einsatz-details-<?php echo _('id') ?>" class="single-view">

	<h1><span class="fa fa-file-text-o"></span>&nbsp;<?php echo _('Details zur Einsatz- ') ?>&nbsp;<?php echo _('Nr.-') ?>&nbsp;<span class="bold"><?php echo $B->get('enr') ?></span>&nbsp;-&nbsp;<?php echo $B->get('haupt_stichwort') ?></h1>

	<?php echo $this->drawMessages() ?>
	
	<div class="left">
		<a class="button" style="margin-left:0;" href="<?php echo $this->tools->buildUrl(ucfirst($_REQUEST['k']), 'index', array('order_by' => $_REQUEST['order_by'], 'period' => $_REQUEST['period'], 'pPage' => $_REQUEST['pPage'], 'order_direction' => $direction, 'date-select' => $_REQUEST['date-select'], 'search' => $_REQUEST['search'])) ?>" onclick="return leavePage();"><span class="fa fa-angle-double-left"></span>&nbsp;<?php echo _('Zurück zur Auswahl') ?></a>
	</div>
	
	<div class="left">
		<a id="report-submit-save" class="button" style="margin-left:20px;" href="#"><span class="fa fa-floppy-o"></span>&nbsp;<?php echo _('Bericht Speichern') ?></a>
	</div>
	
	<div class="left">
		<a class="button" style="margin-left:20px;" href="<?php echo $this->tools->buildUrl(ucfirst($_REQUEST['k']), $_REQUEST['action'], array('cmd' => 'to-pdf', 'eid' => $B->get('eid'), 'typ' => strtolower($this->getReportType($B->get('typ'))))) ?>" onclick="return leavePage();"><span class="fa fa-print"></span>&nbsp;<?php echo _('Drucken (PDF)') ?></a>
	</div>
	
	<div class="right">
		<a class="button" href="<?php echo $this->tools->buildUrl(ucfirst($_REQUEST['k']), $_REQUEST['action'], array('cmd' => 'to-pdf', 'status' => 'finish', 'eid' => $B->get('eid'), 'typ' => strtolower($this->getReportType($B->get('typ'))))) ?>" onclick="return leavePage();"><span class="fa fa-file-pdf-o"></span>&nbsp;<?php echo _('Bericht abschließen (PDF)') ?></a>
	</div>
	<div class="clear"></div>
	<br />
	
	<div id="report-view-title-hilfe" class="report-view-title">
		<h3 class="left"><?php echo $this->getReportType($B->get('typ')) ?> <?php echo _('Thüringen') ?></h3><p class="right"><img src="gfx/thueringen_logo.png" alt="Thüringen" /></p>
		<div class="clear"></div>
	</div>
	
	<?php $html = Html_Factory::getHtml('forms') ?>
	<?php echo $html->drawFormStart('post', $this->tools->buildUrl(ucfirst($_REQUEST['k']), 'save', array('tmpl' => 'edit_hilfeleistung')), '', array('class' => 'report-save-form')) ?>
	
	<!-- uebergeben der Benutzer ID (Bearbeiter)  -->
		<input type="hidden" name="user-id" value="<?php echo $this->user->get('id') ?>" />
	<!-- uebergeben der Benutzer ID (Bearbeiter)  -->
	
	<!-- uebergeben der Einsatz ID (Oracle DB)  -->
		<input type="hidden" name="eid" value="<?php echo $_REQUEST['eid'] ?>" />
	<!-- uebergeben der Einsatz ID (Oracle DB)  -->
	
	<!-- uebergeben der Einsatz Bericht Typ Brand/ TH  -->
		<input type="hidden" name="bericht-type" value="<?php echo strtolower($this->getReportType($B->get('typ'))) ?>" />
	<!-- uebergeben der Einsatz Bericht Typ Brand/ TH  -->
	
	<div id="content-tabs">
		<p id="tab_page1" class="switch-tab active"><span class="tab_1"><?php echo _('Seite 1') ?></span></p>
		<p id="tab_page2" class="switch-tab"><span class="tab_2"><?php echo _('Seite 2') ?></span></p>
		<div class="clear"></div>
	</div>
	
	<div class="report-content-wrap" id="tab_1">
	
		<div class="content-grid-col2 report-content left">
			
			<div class="form-row">
				<?php $html->drawFormInput('landkreis', _('Landkreis/ kreisfr. Stadt'), $this->getConf('landkreis_kreisfreie_stadt'), '', array('class' => 'right', 'readonly' => true)) ?><div class="clear"></div>
				<?php $html->drawFormInput('gemeinde', _('Gemeinde'), $this->getConf('gemeinde'), '', array('class' => 'right', 'readonly' => true)) ?><div class="clear"></div>
				<?php $html->drawFormInput('ident_nr', _('Ident.- Nr. Gemeinde'), $this->getConf('gemeinde_ident_nr'), '', array('class' => 'right', 'readonly' => true)) ?><div class="clear"></div>
				<?php $html->drawFormInput('einsatz_nr', _('Einsatznummer'), $B->get('enr'), strtolower($_REQUEST['k']), array('class' => 'right', 'readonly' => true)) ?><div class="clear"></div>
				<br />
				<p class="left content-grid-col3">&nbsp;</p>
				
				<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[report_art]" value="0" />
				
				<div class="form_field left content-grid-col4">	
					<label for="report_art_haupt"><?php echo _('Hauptbericht') ?>:
					<input class="right radiocheck art" id="report_art_haupt" name="<?php echo strtolower($_REQUEST['k']) ?>[report_art]" value="haupt" type="checkbox" <?php echo ($B->get('report_art') == 'haupt' || $B->get('report_art') == '')? 'checked="checked"':'' ?> /></label>
				</div>
				<div class="form_field right content-grid-col4">
					<label for="report_art_neben"><?php echo _('Nebenbericht') ?>:
					<input class="right radiocheck art" id="report_art_neben" name="<?php echo strtolower($_REQUEST['k']) ?>[report_art]" value="neben" type="checkbox" <?php echo ($B->get('report_art') == 'neben')? 'checked="checked"':'' ?> /></label>
				</div>
				<div class="clear"></div>
			</div>
			
			<div class="form-row">
				<?php $html->drawFormInput('anrufer_name', _('Anrufer Name'), $B->get('anrufer_name'), '', array('class' => 'right')) ?><div class="clear"></div>
				<?php $html->drawFormInput('anrufer_vorname', _('Anrufer Vorname'), $B->get('anrufer_vorname'), '', array('class' => 'right')) ?><div class="clear"></div>
				<?php $html->drawFormInput('anrufer_telefonnummer', _('Anrufer Tel.- Nr.'), $B->get('anrufer_telefonnummer'), '', array('class' => 'right')) ?><div class="clear"></div>
			</div>
			
			<div class="form-row">
				<p style="margin-top:5px;" class="left bold content-grid-col3"><?php echo _('Alarm durch') ?>:</p>
				<div class="left content-grid-col4">
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[alarm_zls]" value="0" />
					<?php $html->drawFormCheckbox('alarm_zls', _('zentrale LTS'), 1, strtolower($_REQUEST['k']), array('checked' => ($B->get('alarm_zls') == '0')? false:true, 'class' => 'right')) ?>
				</div>				
				<div class="right content-grid-col4">
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[alarm_hand]" value="0" />
					<?php $html->drawFormCheckbox('alarm_hand', _('Sirene hand.'), 1, strtolower($_REQUEST['k']), array('checked' => ($B->get('alarm_hand') == '1')? true:false,'class' => 'right')) ?>
				</div>
				<div class="clear"></div>

				<p style="margin-top:7px;" class="left bold label content-grid-col3"><?php echo _('Alarmzeit') ?>:</p>
				<div class="left content-grid-col4">
					<?php $html->drawFormInput('alarmzeit_datum', _('Datum'), date('d.m.Y', $B->get('alarm')), strtolower($_REQUEST['k']), array('readonly' => true, 'class' => 'form-date-time right', 'font-ico' => 'fa-calendar')) ?>
				</div>
				<div class="right content-grid-col3">
					<?php $html->drawFormInput('alarmzeit_uhrzeit', _('Uhrzeit'), date('H:i:s', $B->get('alarm')), strtolower($_REQUEST['k']), array('readonly' => true, 'class' => 'form-date-time right', 'type' => 'time', 'placeholder' => 'hh:mm')) ?>
				</div>
				<div class="clear"></div>
				<!-- uebergeben des Einsatzbeginns -->
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[einsatz_beginn]" value="<?php echo $B->get('einsatz_beginn') ?>" />
				<!-- uebergeben des Einsatzbeginns  -->
			</div>
			
			<div class="form-row">
				<p class="left bold label content-grid-col3"><?php echo _('eigener') ?><br /><?php echo _('Ausrückebereich') ?>:</p>
				
				<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[eigener_ausrueckebereich]" value="0" />
				
				<div class="form_field radio_field left content-grid-col4">
					<label for="report_ausrueckebereich-eigener_ja"><?php echo _('Ja') ?>:</label>
					<input class="right  radiocheck ausrueckebereich-eigener" id="report_ausrueckebereich-eigener_ja" name="<?php echo strtolower($_REQUEST['k']) ?>[eigener_ausrueckebereich]" value="ja" type="checkbox" <?php echo ($B->get('eigener_ausrueckebereich') == 'ja')? 'checked="checked"':'' ?> />
				</div>
				<div class="form_field radio_field right content-grid-col4">
					<label for="report_ausrueckebereich-eigener_nein"><?php echo _('Nein') ?>:</label>
					<input class="right radiocheck ausrueckebereich-eigener" id="report_ausrueckebereich-eigener_nein" name="<?php echo strtolower($_REQUEST['k']) ?>[eigener_ausrueckebereich]" value="nein" type="checkbox" <?php echo ($B->get('eigener_ausrueckebereich') == 'nein')? 'checked="checked"':'' ?> />
				</div>
				<div class="clear"></div>
				
				<?php $html->drawFormInput('entfernung_einsatzstelle', _('Entfernung zur E- Stelle (km)'), $B->get('entfernung_einsatzstelle'), strtolower($_REQUEST['k']), array('class' => 'right small-text', 'bold-label' => true)) ?>
				<div class="clear"></div>
			</div>
			
			<div class="form-row">

			 	<p class="bold"><?php echo _('Fehlalarmierung') ?></p>
				<br />
							
				<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[fehlalarm_blind]" value="0" />		
				<?php $html->drawFormCheckbox('fehlalarm_blind', _('blinder Alarm'), 1, strtolower($_REQUEST['k']), array('class' => 'right radiocheck fehlalarm', 'checked' => ($B->get('fehlalarm_blind') == '1')? true:false)) ?>
				<div class="clear"></div>
				
				<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[fehlalarm_boeswillig]" value="0" />
				<?php $html->drawFormCheckbox('fehlalarm_boeswillig', _('böswilliger Alarm'), 1, strtolower($_REQUEST['k']), array('class' => 'right radiocheck fehlalarm', 'checked' => ($B->get('fehlalarm_boeswillig') == '1')? true:false)) ?>
				<div class="clear"></div>
				
				<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[fehlalarm_fehler_gma]" value="0" />
				<?php $html->drawFormCheckbox('fehlalarm_fehler_gma', _('Fehlalarm GMA'), 1, strtolower($_REQUEST['k']), array('class' => 'right radiocheck fehlalarm', 'checked' => ($B->get('fehlalarm_fehler_gma') == '1')? true:false)) ?>
				<div class="clear"></div>
				
				<?php $html->drawFormInput('fehlalarm_sonstige', _('Sonstige'), $B->get('fehlalarm_sonstige'), strtolower($_REQUEST['k']), array('class' => 'right')) ?>
				<div class="clear"></div>
				
			</div>
			<!--
			<div class="form-row">
				<?php $html->drawFormInput('personal_bereitstellung', _('In Bereitstellung (Anzahl)'), $B->get('personal_bereitstellung'), strtolower($_REQUEST['k']), array('class' => 'right small-text', 'bold-label' => true)) ?><div class="clear"></div>
			</div>
			-->
			
			<div class="form-row">
				<p class="left bold label content-grid-col3"><?php echo _('GMA vorhanden') ?>:</p>
				
				<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[gma_vorhanden]" value="0" />
				
				<div class="form_field radio_field left content-grid-col4">
					<label for="report_gma-vorhanden_ja"><?php echo _('Ja') ?>:</label>
					<input class="right  radiocheck gma-vorhanden" id="report_gma-vorhanden_ja" name="<?php echo strtolower($_REQUEST['k']) ?>[gma_vorhanden]" value="ja" type="checkbox" <?php echo ($B->get('gma_vorhanden') == 'ja')? 'checked="checked"':'' ?> />
				</div>
				<div class="form_field radio_field right content-grid-col4">
					<label for="report_gma-vorhanden_nein"><?php echo _('Nein') ?>:</label>
					<input class="right radiocheck gma-vorhanden" id="report_gma-vorhanden_nein" name="<?php echo strtolower($_REQUEST['k']) ?>[gma_vorhanden]" value="nein" type="checkbox" <?php echo ($B->get('gma_vorhanden') == 'nein')? 'checked="checked"':'' ?>/>
				</div>
				<div class="clear"></div>
			</div>
			
			<div class="form-row">
			
				<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[gma_ausgeloest]" value="0" />
			
				<div class="form_field radio_field left content-grid-col3">
					<label class="bold" for="report_gma-ausgeloest_ja"><?php echo _('GMA ausgelöst') ?>:</label>
					<input class="right radiocheck gma-ausgeloest" id="report_gma-ausgeloest_ja" name="<?php echo strtolower($_REQUEST['k']) ?>[gma_ausgeloest]" value="ja" type="checkbox" <?php echo ($B->get('gma_ausgeloest') == 'ja')? 'checked="checked"':'' ?> />
				</div>
				<div class="form_field radio_field right content-grid-col2">
					<label class="bold" for="report_gma-ausgeloest_nein"><?php echo _('GMA nicht ausgelöst') ?>:</label>
					<input class="right radiocheck gma-ausgeloest" id="report_gma-ausgeloest_nein" name="<?php echo strtolower($_REQUEST['k']) ?>[gma_ausgeloest]" value="nein" type="checkbox" <?php echo ($B->get('gma_ausgeloest') == 'nein')? 'checked="checked"':'' ?> />
				</div>
				<div class="clear"></div>
			</div>
				
			<div class="form-row">
				<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[gefahr_freisetzung_gef_stoffe]" value="0" />
				<?php $html->drawFormCheckbox('gefahr_freisetzung_gef_stoffe', _('Gefährdung durch Freisetzung von gefährlichen Stoffen'), 1, strtolower($_REQUEST['k']), array('checked' => ($B->get('gefahr_freisetzung_gef_stoffe') == '1')? true:false, 'class' => 'right', 'bold-label' => true)) ?><div class="clear"></div>
			</div>
			
			<div class="form-row" style="height:89px">&nbsp;</div>
			
		</div>
		
		<div class="content-grid-col2 report-content right">
			
			<div class="form-row">
			 	<?php $html->drawFormInput('stichwort', _('Einsatzstichwort'), $B->get('stichwort'), '', array('class' => 'right', 'bold-label' => true)) ?><div class="clear"></div>
				<?php $html->drawFormInput('objektname', _('Einsatzstelle'), $B->get('objektname'), '', array('class' => 'right')) ?><div class="clear"></div>
				<?php $html->drawFormInput('adresse1', _('Adresse'), $B->get('adresse1').' '.$B->get('hnr'), '', array('class' => 'right')) ?><div class="clear"></div>
				<?php $html->drawFormInput('ort', _('Ort'), $B->get('ort').'/ '.$B->get('ortsteil'), '', array('class' => 'right')) ?><div class="clear"></div>
			</div>
			
			<div class="form-row">
				<?php $html->drawFormInput('einsatzobjekt_eigentuemer', _('Eigentümer'), $B->get('einsatzobjekt_eigentuemer'), strtolower($_REQUEST['k']), array('class' => 'right', 'bold-label' => true)) ?><div class="clear"></div>
				<?php $html->drawFormInput('einsatzobjekt_eigentuemer_name', _('Name'), $B->get('einsatzobjekt_eigentuemer_name'), strtolower($_REQUEST['k']), array('class' => 'right')) ?><div class="clear"></div>
				<?php $html->drawFormInput('einsatzobjekt_eigentuemer_adresse', _('Anschrift'), $B->get('einsatzobjekt_eigentuemer_adresse'), strtolower($_REQUEST['k']), array('class' => 'right')) ?><div class="clear"></div>
				<br />
				<p class="right"><?php echo _('Mehrere Eigentümer im Feld "Einsatzbericht" erfassen!') ?></p>
				<div class="clear"></div>
			</div>
			<div class="form-row">
				<?php $html->drawFormInput('einsatzobjekt_geschaedigter', _('Geschädigter'), $B->get('einsatzobjekt_geschaedigter'), strtolower($_REQUEST['k']), array('class' => 'right', 'bold-label' => true)) ?><div class="clear"></div>
				<?php $html->drawFormInput('einsatzobjekt_geschaedigter_name', _('Name'), $B->get('einsatzobjekt_geschaedigter_name'), strtolower($_REQUEST['k']), array('class' => 'right')) ?><div class="clear"></div>
				<?php $html->drawFormInput('einsatzobjekt_geschaedigter_adresse', _('Anschrift'), $B->get('einsatzobjekt_geschaedigter_adresse'), strtolower($_REQUEST['k']), array('class' => 'right')) ?><div class="clear"></div>
				<br />
				<p class="right"><?php echo _('Mehrere Geschädigte im Feld "Einsatzbericht" erfassen!') ?></p>
				<div class="clear"></div>
			</div>
			
			<div class="form-row">
			 	<?php $html->drawFormInput('personen_rettung_anzahl_gesamt', _('Anzahl geretteter Personen'), $B->get('personen_rettung_anzahl_gesamt'), strtolower($_REQUEST['k']), array('class' => 'right small-text readonly', 'bold-label' => true, 'readonly' => true)) ?><div class="clear"></div>
				<?php $html->drawFormInput('personen_rettung_anzahl_baulich', _('davon über baulichen Rettungsweg'), $B->get('personen_rettung_anzahl_baulich'), strtolower($_REQUEST['k']), array('class' => 'right small-text personen_rettung')) ?><div class="clear"></div>
				<?php $html->drawFormInput('personen_rettung_anzahl_hubrettung', _('davon über Hubrettungsfahrzeuge'), $B->get('personen_rettung_anzahl_hubrettung'), strtolower($_REQUEST['k']), array('class' => 'right small-text personen_rettung')) ?><div class="clear"></div>
				<?php $html->drawFormInput('personen_rettung_anzahl_tragbar', _('davon über tragbare Leitern'), $B->get('personen_rettung_anzahl_tragbar'), strtolower($_REQUEST['k']), array('class' => 'right small-text personen_rettung')) ?><div class="clear"></div>
				<?php $html->drawFormInput('personen_rettung_anzahl_sonstiges', _('davon über Sonstiges'), $B->get('personen_rettung_anzahl_sonstiges'), strtolower($_REQUEST['k']), array('class' => 'right small-text personen_rettung')) ?><div class="clear"></div>
			</div>
			
			<div class="form-row">
				<?php $html->drawFormInput('tiere_rettung_anzahl_gesamt', _('Anzahl geretteter Tiere'), $B->get('tiere_rettung_anzahl_gesamt'), strtolower($_REQUEST['k']), array('class' => 'right small-text', 'bold-label' => true)) ?><div class="clear"></div>
			</div>
			
			<div class="form-row">
				<?php $html->drawFormInput('personal_schaeden_anzahl_gesamt', _('Anzahl geschädigter Feuerwehrangehöriger'), $B->get('personal_schaeden_anzahl_gesamt'), strtolower($_REQUEST['k']), array('class' => 'right small-text readonly', 'bold-label' => true, 'readonly' => true)) ?><div class="clear"></div>
				<?php $html->drawFormInput('personal_schaeden_anzahl_tod', _('davon tödlich Verunglückte'), $B->get('personal_schaeden_anzahl_tod'), strtolower($_REQUEST['k']), array('class' => 'right small-text personal_schaeden')) ?><div class="clear"></div>
				<?php $html->drawFormInput('personal_schaeden_anzahl_verletzt', _('davon Verletzte/ Verunglückte'), $B->get('personal_schaeden_anzahl_verletzt'), strtolower($_REQUEST['k']), array('class' => 'right small-text personal_schaeden')) ?><div class="clear"></div>
			</div>
			
			<div class="form-row">
				<?php $html->drawFormInput('personen_schaeden_anzahl_gesamt', _('Anzahl geschädigter anderer Personen'), $B->get('personen_schaeden_anzahl_gesamt'), strtolower($_REQUEST['k']), array('class' => 'right small-text readonly', 'bold-label' => true, 'readonly' => true)) ?><div class="clear"></div>
				<?php $html->drawFormInput('personen_schaeden_anzahl_tod', _('davon tödlich Verunglückte'), $B->get('personen_schaeden_anzahl_tod'), strtolower($_REQUEST['k']), array('class' => 'right small-text personen_schaeden')) ?><div class="clear"></div>
				<?php $html->drawFormInput('personen_schaeden_anzahl_verletzt', _('davon Verletzte/ Verunglückte'), $B->get('personen_schaeden_anzahl_verletzt'), strtolower($_REQUEST['k']), array('class' => 'right small-text personen_schaeden')) ?><div class="clear"></div>
			</div>
			
		</div>
		<div class="clear"></div>
		
		<div class="report-content">
			
			<div class="form-row">
				<p class="bold label"><?php echo _('Klassifikation des Hilfeleistungseinsatzes') ?></p>
				<br />
				
				<div class="left" style="width:50%">
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[klassifikation_menschen_in_notlage]" value="0" />
					<?php $html->drawFormCheckbox('klassifikation_menschen_in_notlage', _('Menschen in Notlage'), 1, strtolower($_REQUEST['k']), array('class' => 'right klassifikation radiocheck', 'checked' => ($B->get('klassifikation_menschen_in_notlage') == '1')? true:false)) ?><div class="clear"></div>
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[klassifikation_gefahren_tiere_insekten]" value="0" />
					<?php $html->drawFormCheckbox('klassifikation_gefahren_tiere_insekten', _('Gefahren durch/ mit Tieren/ Insekten'), 1, strtolower($_REQUEST['k']), array('class' => 'right klassifikation radiocheck', 'checked' => ($B->get('klassifikation_gefahren_tiere_insekten') == '1')? true:false)) ?><div class="clear"></div>
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[klassifikation_betriebsunfall]" value="0" />
					<?php $html->drawFormCheckbox('klassifikation_betriebsunfall', _('Betriebsunfall'), 1, strtolower($_REQUEST['k']), array('class' => 'right klassifikation radiocheck', 'checked' => ($B->get('klassifikation_betriebsunfall') == '1')? true:false)) ?><div class="clear"></div>
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[klassifikation_einsturz]" value="0" />
					<?php $html->drawFormCheckbox('klassifikation_einsturz', _('Einsturz baulicher Anlagen'), 1, strtolower($_REQUEST['k']), array('class' => 'right klassifikation radiocheck', 'checked' => ($B->get('klassifikation_einsturz') == '1')? true:false)) ?><div class="clear"></div>
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[klassifikation_amtshilfe_polizei]" value="0" />
					<?php $html->drawFormCheckbox('klassifikation_amtshilfe_polizei', _('Amtshilfe Polizei'), 1, strtolower($_REQUEST['k']), array('class' => 'right klassifikation radiocheck', 'checked' => ($B->get('klassifikation_amtshilfe_polizei') == '1')? true:false)) ?><div class="clear"></div>
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[klassifikation_sonstige]" value="0" />
					<?php $html->drawFormCheckbox('klassifikation_sonstige', _('Sonstiger Einsatz'), 1, strtolower($_REQUEST['k']), array('class' => 'right klassifikation radiocheck', 'checked' => ($B->get('klassifikation_sonstige') == '1')? true:false)) ?><div class="clear"></div>
				
				</div>
				<div class="right" style="width:45%">
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[klassifikation_verkehrsunfall_stoerung]" value="0" />
					<?php $html->drawFormCheckbox('klassifikation_verkehrsunfall_stoerung', _('Verkehrsunfälle- und störung'), 1, strtolower($_REQUEST['k']), array('class' => 'right klassifikation radiocheck', 'checked' => ($B->get('klassifikation_verkehrsunfall_stoerung') == '1')? true:false)) ?><div class="clear"></div>
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[klassifikation_wasser_sturm]" value="0" />
					<?php $html->drawFormCheckbox('klassifikation_wasser_sturm', _('Wasser- und Sturmschaden'), 1, strtolower($_REQUEST['k']), array('class' => 'right klassifikation radiocheck', 'checked' => ($B->get('klassifikation_wasser_sturm') == '1')? true:false)) ?><div class="clear"></div>
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[klassifikation_unterstuetzung_rettungsdienst]" value="0" />
					<?php $html->drawFormCheckbox('klassifikation_unterstuetzung_rettungsdienst', _('Unterstützung Rettungsdienst'), 1, strtolower($_REQUEST['k']), array('class' => 'right klassifikation radiocheck', 'checked' => ($B->get('klassifikation_unterstuetzung_rettungsdienst') == '1')? true:false)) ?><div class="clear"></div>
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[klassifikation_gefaehrliche_stoffe]" value="0" />
					<?php $html->drawFormCheckbox('klassifikation_gefaehrliche_stoffe', _('Einsatz mit gefährlichen Stoffen u. Gütern'), 1, strtolower($_REQUEST['k']), array('class' => 'right klassifikation radiocheck', 'checked' => ($B->get('klassifikation_gefaehrliche_stoffe') == '1')? true:false)) ?><div class="clear"></div>
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[klassifikation_oelspur]" value="0" />
					<?php $html->drawFormCheckbox('klassifikation_oelspur', _('Ölunfall/ Ölspur'), 1, strtolower($_REQUEST['k']), array('class' => 'right klassifikation radiocheck', 'checked' => ($B->get('klassifikation_oelspur') == '1')? true:false)) ?>
					<?php $html->drawFormInput('klassifikation_sonstige_name', _('Sonstige Einsatz (Text)'), $B->get('klassifikation_sonstige_name'), strtolower($_REQUEST['k']), array('class' => 'right')) ?>
				</div>
				<div class="clear"></div>
			</div>
			
		</div>
		
		<!-- 
		<div class="report-content">
			<div class="form-row">
				<?php //$html->drawFormInput('klassifikation_sonstiger_einsatz', _('Sonstiger Einsatz'), $B->get('klassifikation_sonstiger_einsatz'), strtolower($_REQUEST['k']), array('class' => 'right', 'style' => 'width:77%', 'bold-label' => true)) ?><div class="clear"></div>
			</div>
		</div>
		-->
		
		<div class="report-content">
			<div class="form-row">
				<?php $html->drawFormTextarea('eingesetzte_geraete', _('Eingesetzte Geräte'), $B->get('eingesetzte_geraete'), strtolower($_REQUEST['k']), array('class' => 'right', 'rows' => '5', 'bold-label' => true)) ?><div class="clear"></div>
			</div>
		</div>
		
		<div class="report-content">
			<div class="form-row">
				<?php $html->drawFormTextarea('verbrauchsmaterial', _('Verbrauchsmaterial'), $B->get('verbrauchsmaterial'), strtolower($_REQUEST['k']), array('class' => 'right', 'rows' => '5', 'bold-label' => true)) ?><div class="clear"></div>
			</div>
		</div>
		
	</div>
	
	<!-- Seite 2 als eigenes Template einbinden -->
		<?php include VIEW_PATH.'/Report/edit_hilfeleistung2.phtml' ?>
	<!-- Seite 2 als eigenes Template einbinden -->
	
	<?php echo $html->drawFormEnde() ?>
	
	<script type="text/javascript">
	//<![CDATA[
	
		$(document).ready(function(){

			setTimeout(function(){ $('.report-save-form').submit(); }, 1200000);

		})	
		
	
	//]]>
	</script>
	
</div>