<div class="report-content-wrap" id="tab_3" style="display:none;">
	<div class="report-content">
		<div class="form-row">
		
			<div class="form-row">
				<p class="bold"><?php echo _('Angaben zu Objekten mit Brandmeldeanlagen') ?></p>
			</div>
			
			<div class="form-row">
				<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[bma_reset]" value="0" />
				<?php $html->drawFormCheckbox('bma_reset', _('Anlage wurde vor Eintreffen der Feuerwehr zurückgesetzt (weiteres Ausfüllen zu Angaben der BMA entfällt)'), 1, strtolower($_REQUEST['k']), array('class' => 'left')) ?>
			</div>
			<div class="clear"></div>
			
			<div class="form-row">
				
				<p class="bold"><?php echo _('Blitzlampe') ?></p>
				
				<div class="left content-grid-col2">
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[blitzlampe_ein]" value="0" />
					<?php $html->drawFormCheckbox('blitzlampe_ein', _('in Funktion'), 1, strtolower($_REQUEST['k']), array('class' => 'left blitzlampe radiocheck')) ?>
				</div>
				<div class="left content-grid-col2">
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[blitzlampe_aus]" value="0" />
					<?php $html->drawFormCheckbox('blitzlampe_aus', _('nicht in Funktion'), 1, strtolower($_REQUEST['k']), array('class' => 'left blitzlampe radiocheck')) ?>
				</div>
				<div class="clear"></div>
			</div>
			
			<div class="form-row">
				
				<p class="bold"><?php echo _('Feuerwehr Schlüsselkasten') ?></p>
				
				<div class="left content-grid-col2">
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[schluesselkasten_ohne]" value="0" />
					<?php $html->drawFormCheckbox('schluesselkasten_ohne', _('am Objekt nicht vorhanden'), 1, strtolower($_REQUEST['k']), array('class' => 'left schluesselkasten radiocheck')) ?>
				</div>
				<div class="left content-grid-col2">
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[schluesselkasten_nicht_zu_oeffnen]" value="0" />
					<?php $html->drawFormCheckbox('schluesselkasten_nicht_zu_oeffnen', _('ließ sich nicht öffnen'), 1, strtolower($_REQUEST['k']), array('class' => 'left schluesselkasten radiocheck')) ?>
				</div>
				<div class="left content-grid-col2">
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[schluesselkasten_geoeffnet]" value="0" />
					<?php $html->drawFormCheckbox('schluesselkasten_geoeffnet', _('wurde geöffnet, Objektschlüssel entnommen'), 1, strtolower($_REQUEST['k']), array('class' => 'left schluesselkasten radiocheck')) ?>
				</div>
				<div class="left content-grid-col2">
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[schluesselkasten_ohne_oeffnen]" value="0" />
					<?php $html->drawFormCheckbox('schluesselkasten_ohne_oeffnen', _('brauchte nicht geöffnet werden'), 1, strtolower($_REQUEST['k']), array('class' => 'left schluesselkasten radiocheck')) ?>
				</div>
				<div class="clear"></div>
			</div>
			
			<div class="form-row">
				
				<p class="bold"><?php echo _('Freischaltelement') ?></p>
				
				<div class="left content-grid-col2">
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[freischaltelement_ohne]" value="0" />
					<?php $html->drawFormCheckbox('freischaltelement_ohne', _('am Objekt nicht vorhanden'), 1, strtolower($_REQUEST['k']), array('class' => 'left freischaltelement radiocheck')) ?>
				</div>
				<div class="left content-grid-col2">
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[freischaltelement_geschlossen]" value="0" />
					<?php $html->drawFormCheckbox('freischaltelement_geschlossen', _('wurde zur Alarmauslösung geschlossen'), 1, strtolower($_REQUEST['k']), array('class' => 'left freischaltelement radiocheck')) ?>
				</div>
				<div class="left content-grid-col2">
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[freischaltelement_nicht_genutzt]" value="0" />
					<?php $html->drawFormCheckbox('freischaltelement_nicht_genutzt', _('wurde zur Alarmauslösung nicht benötigt'), 1, strtolower($_REQUEST['k']), array('class' => 'left freischaltelement radiocheck')) ?>
				</div>
				<div class="clear"></div>
			</div>
			
			<div class="form-row">
				
				<p class="bold"><?php echo _('Objektschlüssel') ?></p>
				
				<div class="left content-grid-col2">
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[objektschluessel_ohne_verwendung]" value="0" />
					<?php $html->drawFormCheckbox('objektschluessel_ohne_verwendung', _('brauchten nicht zur Anwendung gebracht werden'), 1, strtolower($_REQUEST['k']), array('class' => 'left objektschluessel radiocheck')) ?>
				</div>
				<div class="left content-grid-col2">
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[objektschluessel_maengel]" value="0" />
					<?php $html->drawFormCheckbox('objektschluessel_maengel', _('Mängel im Schließsystem festgestellt'), 1, strtolower($_REQUEST['k']), array('class' => 'left objektschluessel radiocheck')) ?>
				</div>
				<div class="left content-grid-col2">
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[objektschluessel_schliesst]" value="0" />
					<?php $html->drawFormCheckbox('objektschluessel_schliesst', _('alle benutzten verschlossenen Türen schließbar'), 1, strtolower($_REQUEST['k']), array('class' => 'left objektschluessel radiocheck')) ?>
				</div>
				<div class="clear"></div>
			</div>
			
			<div class="form-row">
				
				<p class="bold"><?php echo _('Angaben zur Melderauslösung') ?></p>
				
				<div class="left content-grid-col2">
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[melderausloesung_ausgeloest]" value="0" />
					<?php $html->drawFormCheckbox('melderausloesung_ausgeloest', _('Melder ausgelöst'), 1, strtolower($_REQUEST['k']), array('class' => 'left melderausloesung radiocheck')) ?>
				</div>
				<div class="left content-grid-col2">
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[melderausloesung_stoerung]" value="0" />
					<?php $html->drawFormCheckbox('melderausloesung_stoerung', _('Mängel im Schließsystem festgestellt'), 1, strtolower($_REQUEST['k']), array('class' => 'left melderausloesung radiocheck')) ?>
				</div>
				<div class="clear"></div>
				
				<div class="margin-left20">
					<div class="left content-grid-col2">
						<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[ausloesegrund_brand]" value="0" />
						<?php $html->drawFormCheckbox('ausloesegrund_brand', _('infolge eines Brandes'), 1, strtolower($_REQUEST['k']), array('class' => 'left ausloesegrund radiocheck')) ?>
					</div>
					<div class="clear"></div>
					<div class="left content-grid-col2">
						<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[ausloesegrund_missbrauch]" value="0" />
						<?php $html->drawFormCheckbox('ausloesegrund_missbrauch', _('infolge Meldermissbrauch (vorsätzlich oder fahrlässing)'), 1, strtolower($_REQUEST['k']), array('class' => 'left ausloesegrund radiocheck')) ?>
					</div>
					<div class="clear"></div>
					<div class="left content-grid-col2">
						<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[ausloesegrund_kenngroesse]" value="0" />
						<?php $html->drawFormCheckbox('ausloesegrund_kenngroesse', _('infolge Brandkenngrößen (Rauch, Wärme, Feuerschein)'), 1, strtolower($_REQUEST['k']), array('class' => 'left ausloesegrund radiocheck')) ?>
					</div>
					<div class="clear"></div>
					<div class="left content-grid-col2">
						<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[ausloesegrund_ohne]" value="0" />
						<?php $html->drawFormCheckbox('ausloesegrund_ohne', _('nicht feststellbar'), 1, strtolower($_REQUEST['k']), array('class' => 'left ausloesegrund radiocheck')) ?>
					</div>
				</div>	
				<div class="clear"></div>
			</div>
			
			<div class="form-row">
				<p class="bold"><?php echo _('auslösender Melder') ?></p>
			</div>
			<div class="form-row">
				<div class="left content-grid-col4">
					<p><?php echo _('Meldergruppe / -nummer') ?></p>
					<div class="left content-grid-col2"><?php $html->drawFormInput('meldergruppe', '', '',strtolower($_REQUEST['k']), array()) ?></div>
					<div class="left content-grid-col2"><?php $html->drawFormInput('meldernummer', '', '',strtolower($_REQUEST['k']), array()) ?></div>
					<div class="clear"></div>
				</div>
				
				<div class="left content-grid-col70-30">
					<p><?php echo _('Gebäudeteil/ Geschoß/ Raumbezeichnung bzw. -nummer') ?></p>
					<?php $html->drawFormInput('melder_ort_beschreibung', '', '',strtolower($_REQUEST['k']), array()) ?>
				</div>
				<div class="clear"></div>
			</div>
			
			<div class="form-row">
				
				<p class="bold"><?php echo _('Gruppenmeldekartei, Lageplantableau, elektronische Einsatzdatei') ?></p>
				
				<div class="left content-grid-col2">
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[gruppenmeldekartei_angewendet]" value="0" />
					<?php $html->drawFormCheckbox('gruppenmeldekartei_angewendet', _('problemlose Anwendung'), 1, strtolower($_REQUEST['k']), array('class' => 'left gruppenmeldekartei radiocheck')) ?>
				</div>
				<div class="left content-grid-col2">
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[gruppenmeldekartei_fehlerhaft]" value="0" />
					<?php $html->drawFormCheckbox('gruppenmeldekartei_fehlerhaft', _('fehlerhafte Angaben'), 1, strtolower($_REQUEST['k']), array('class' => 'left gruppenmeldekartei radiocheck')) ?>
				</div>
				<div class="left content-grid-col2">
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[gruppenmeldekartei_nicht_angewendet]" value="0" />
					<?php $html->drawFormCheckbox('gruppenmeldekartei_nicht_angewendet', _('wurde nicht zur Anwendung gebracht'), 1, strtolower($_REQUEST['k']), array('class' => 'left gruppenmeldekartei radiocheck')) ?>
				</div>
				<div class="clear"></div>
			</div>
			
			<div class="form-row">
				<p class="bold"><?php echo _('Mängel und Probleme sind im "Bericht des Einsatzleiters" zu schildern!') ?></p>
			</div>
			
		</div>
	</div>
</div>