<?php 
/**
 * template wiedervorlagen 
 */
?>
<div id="einsatz-review-wrap">		
	<table id="einsatz-review-list" class="content-list-table">
		<thead>
			<tr>
				<th class="check-col"><?php echo _('Typ') ?></th>
				<th><?php echo _('Einsatznummer') ?></th>
				<th><?php echo _('Stichwort') ?></th>
				<th><?php echo _('Beginn') ?></th>
				<th><?php echo _('Alarmierung') ?></th>
				<th><?php echo _('Stadt') ?></th>
				<th><?php echo _('Straße') ?></th>
			</tr>
		</thead>
		<tbody>
			<?php if ($this->tools->isSizedArray($this->view['data']['review'])) { ?>
			<?php $i = 1; foreach ($this->view['data']['review'] as $einsatz) { $i++; ?>
			<tr <?php echo (($i % 2) == 0)? 'class="even"':'class="odd"' ?>>
				<td class="check-col" title="<?php echo $einsatz['typ'] ?>"><span class="fa <?php echo $this->getEventIcon($einsatz['typ']) ?> <?php echo $this->getIconColor($einsatz['typ']) ?>"></span></td>
				<td>
					<a href="<?php echo $this->tools->buildUrl(ucfirst($_REQUEST['k']), $_REQUEST['action'], array('eid' => $einsatz['eid'], 'tmpl' => 'edit_'.strtolower ($einsatz['typ']))) ?>"><strong><?php echo $einsatz['enr'] ?></strong></a><br />
					<a href="<?php echo $this->tools->buildUrl(ucfirst($_REQUEST['k']), $_REQUEST['action'], array('eid' => $einsatz['eid'], 'tmpl' => 'edit_'.strtolower ($einsatz['typ']))) ?>"><span class="view-details"><?php echo _('bearbeiten') ?></span></a>
					<!-- 
					&nbsp;|<a href="<?php echo $this->tools->buildUrl(ucfirst($_REQUEST['k']), 'reset', array('eid' => $einsatz['eid'])) ?>"><span class="red" title="<?php echo _('wird wieder zum offenen Einsatz') ?>"><?php echo _('freigeben') ?></span></a>
					-->
				</td>
				<td><?php echo $einsatz['stichwort'] ?></td>
				<td><?php echo date('d.m.Y H:i:s', $einsatz['beginn']) ?></td>
				<td><?php echo date('d.m.Y H:i:s', $einsatz['alarm']) ?></td>
				<td><?php echo $einsatz['ort'] ?></td>
				<td><?php echo $einsatz['adresse1'] ?></td>
			</tr>
			<?php } ?>
			<?php } else { ?>
				<tr><td colspan="11" class="empty-data"><?php echo _('Es sind keine Einträge in der Wiedervorlage verhanden.') ?></td></tr>
			<?php } ?>
		</tbody>
		
		<tfoot>
			<tr>
				<th class="check-col"><?php echo _('Typ') ?></th>
				<th><?php echo _('Einsatznummer') ?></th>
				<th><?php echo _('Stichwort') ?></th>
				<th><?php echo _('Beginn') ?></th>
				<th><?php echo _('Alarmierung') ?></th>
				<th><?php echo _('Stadt') ?></th>
				<th><?php echo _('Straße') ?></th>
			</tr>
		</tfoot>
	</table>
</div>
<br />
	
	
		