<?php 
/**
 * Template Einsatzdetails
 */
$Einsatz = $this->view['data'];
//$this->tools->debug($Einsatz->eData);
?>

<div id="einsatz-details-<?php echo _('id') ?>" class="single-view">

	<h1><span class="fa fa-file-text-o"></span>&nbsp;<?php echo _('Details zur Einsatz- ') ?>&nbsp;<?php echo _('Nr.-') ?>&nbsp;<span class="bold"><?php echo $Einsatz->get('EINSATZ_NUMMER') ?></span>&nbsp;-&nbsp;<?php echo $Einsatz->get('EINSATZ_STICHWORT') ?></h1>

	<?php echo $this->drawMessages() ?>
	
	<p class="left"><?php echo _('Zum Bearbeiten müssen die Daten erstmalig gespeichert werden!') ?></p>
	<div class="left">
		<a class="button" href="<?php echo $this->tools->buildUrl(ucfirst($_REQUEST['k']), $_REQUEST['action'], array('order_by' => $_REQUEST['order_by'], 'period' => $_REQUEST['period'], 'pPage' => $_REQUEST['pPage'], 'order_direction' => $direction, 'date-select' => $_REQUEST['date-select'], 'search' => $_REQUEST['search'])) ?>"><span class="fa fa-angle-double-left"></span>&nbsp;<?php echo _('Zurück zur Auswahl') ?></a>
	</div>
	<div class="right">
		<a id="report-submit-save" class="button" href="#"><span class="fa fa-floppy-o"></span>&nbsp;<?php echo _('Bericht Speichern') ?></a>
	</div>
	<div class="clear"></div>
	<br />
	
	<div id="report-view-title-hilfe" class="report-view-title">
		<h3 class="left"><?php echo $this->getReportType($Einsatz->get('EINSATZ_HAUPTSTICHWORT')) ?> <?php echo _('Thüringen') ?></h3><p class="right"><img src="gfx/thueringen_logo.png" alt="Thüringen" /></p>
		<div class="clear"></div>
	</div>
	
	<?php $html = Html_Factory::getHtml('forms') ?>
	<?php echo $html->drawFormStart('post', $this->tools->buildUrl(ucfirst($_REQUEST['k']), 'save', array('tmpl' => 'hilfeleistung')), '', array('class' => 'report-save-form')) ?>
	
	<!-- uebergeben der Benutzer ID (Bearbeiter)  -->
		<input type="hidden" name="user-id" value="<?php echo $this->user->get('id') ?>" />
	<!-- uebergeben der Benutzer ID (Bearbeiter)  -->
	
	<!-- uebergeben der Einsatz ID (Oracle DB)  -->
		<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[eid]" value="<?php echo $_REQUEST['eid'] ?>" />
	<!-- uebergeben der Einsatz ID (Oracle DB)  -->
	
	<!-- uebergeben der Einsatz Bericht Typ Brand/ TH  -->
		<input type="hidden" name="bericht-type" value="<?php echo strtolower($this->getReportType($Einsatz->get('EINSATZ_HAUPTSTICHWORT'))) ?>" />
	<!-- uebergeben der Einsatz Bericht Typ Brand/ TH  -->
	
	<!-- uebergeben des Hauptstichwortes  -->
		<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[einsatz_haupt_stichwort]" value="<?php echo $Einsatz->get('EINSATZ_HAUPTSTICHWORT') ?>" />
	<!-- uebergeben des Hauptstichwortes  -->
	
	<div id="content-tabs">
		<p id="tab_page1" class="switch-tab active"><span class="tab_1"><?php echo _('Seite 1') ?></span></p>
		<p id="tab_page2" class="switch-tab"><span class="tab_2"><?php echo _('Seite 2') ?></span></p>
		<div class="clear"></div>
	</div>
	
	<div class="report-content-wrap" id="tab_1">
	
		<div class="content-grid-col2 report-content left">
			
			<div class="form-row">
				<?php $html->drawFormInput('landkreis', _('Landkreis/ kreisfr. Stadt'), $this->getConf('landkreis_kreisfreie_stadt'), '', array('class' => 'right')) ?><div class="clear"></div>
				<?php $html->drawFormInput('gemeinde', _('Gemeinde'), $this->getConf('gemeinde'), '', array('class' => 'right')) ?><div class="clear"></div>
				<?php $html->drawFormInput('ident_nr', _('Ident.- Nr. Gemeinde'), $this->getConf('gemeinde_ident_nr'), '', array('class' => 'right')) ?><div class="clear"></div>
				<?php $html->drawFormInput('einsatz_nr', _('Einsatznummer'), $Einsatz->get('EINSATZ_NUMMER'), strtolower($_REQUEST['k']), array('class' => 'right')) ?><div class="clear"></div>
				<br />
				<p class="left content-grid-col3">&nbsp;</p>
				
				<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[report_art]" value="0" />
				
				<div class="form_field left content-grid-col4">
					<label for="report_art_haupt"><?php echo _('Hauptbericht') ?>:
					<input class="right" id="report_art_haupt" name="<?php echo strtolower($_REQUEST['k']) ?>[report_art]" value="haupt" type="radio" checked="checked" /></label>
				</div>
				<div class="form_field right content-grid-col4">
					<label for="report_art_neben"><?php echo _('Nebenbericht') ?>:
					<input class="right" id="report_art_neben" name="<?php echo strtolower($_REQUEST['k']) ?>[report_art]" value="neben" type="radio" /></label>
				</div>
				<div class="clear"></div>
			</div>
			
			<div class="form-row">
				<?php $html->drawFormInput('anrufer_name', _('Anrufer Name'), $Einsatz->get('ANRUFER_NAME'), strtolower($_REQUEST['k']), array('class' => 'right')) ?><div class="clear"></div>
				<?php $html->drawFormInput('anrufer_vorname', _('Anrufer Vorname'), $Einsatz->get('ANRUFER_VORNAME'), strtolower($_REQUEST['k']), array('class' => 'right')) ?><div class="clear"></div>
				<?php $html->drawFormInput('anrufer_telefonnummer', _('Anrufer Tel.- Nr.'), $Einsatz->get('ANRUFER_TELEFONNUMMER'), strtolower($_REQUEST['k']), array('class' => 'right')) ?><div class="clear"></div>
			</div>
			
			<div class="form-row">
				<p style="margin-top:5px;" class="left bold content-grid-col3"><?php echo _('Alarm durch') ?>:</p>
				<div class="left content-grid-col4">
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[alarm_zls]" value="0" />
					<?php $html->drawFormCheckbox('alarm_zls', _('zentrale LTS'), 1, strtolower($_REQUEST['k']), array('checked' => ($Einsatz->get('EINSATZ_ALARM') != '')? true:false, 'class' => 'right')) ?>
				</div>				
				<div class="right content-grid-col4">
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[alarm_hand]" value="0" />
					<?php $html->drawFormCheckbox('alarm_hand', _('Sirene hand.'), 1, strtolower($_REQUEST['k']), array('class' => 'right')) ?>
				</div>
				<div class="clear"></div>

				<p style="margin-top:7px;" class="left bold label content-grid-col3"><?php echo _('Alarmzeit') ?>:</p>
				<div class="left content-grid-col4">
					<?php $html->drawFormInput('alarmzeit_datum', _('Datum'), date('d.m.Y', strtotime($Einsatz->get('EINSATZ_ALARM'))), strtolower($_REQUEST['k']), array('class' => 'form-date-time right datepicker', 'font-ico' => 'fa-calendar')) ?>
				</div>
				<div class="right content-grid-col3">
					<?php $html->drawFormInput('alarmzeit_uhrzeit', _('Uhrzeit'), date('H:i:s', strtotime($Einsatz->get('EINSATZ_ALARM'))), strtolower($_REQUEST['k']), array('class' => 'form-date-time right', 'type' => 'time', 'placeholder' => 'hh:mm')) ?>
				</div>
				<div class="clear"></div>
				<!-- uebergeben des Einsatzbeginns -->
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[einsatz_beginn]" value="<?php echo $Einsatz->get('EINSATZ_ALARM') ?>" />
				<!-- uebergeben des Einsatzbeginns  -->
			</div>
			
			<div class="form-row">
				<p class="left bold label content-grid-col3"><?php echo _('eigener') ?><br /><?php echo _('Ausrückebereich') ?>:</p>
				
				<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[eigener_ausrueckebereich]" value="0" />
				
				<div class="form_field radio_field left content-grid-col4">
					<label for="report_eigener_ausrueckebereich_ja"><?php echo _('Ja') ?>:</label>
					<input class="right" id="report_eigener_ausrueckebereich_ja" name="<?php echo strtolower($_REQUEST['k']) ?>[eigener_ausrueckebereich]" value="ja" type="radio" checked="checked" />
				</div>
				<div class="form_field radio_field right content-grid-col4">
					<label for="report_eigener_ausrueckebereich_nein"><?php echo _('Nein') ?>:</label>
					<input class="right" id="report_eigener_ausrueckebereich_nein" name="<?php echo strtolower($_REQUEST['k']) ?>[eigener_ausrueckebereich]" value="nein" type="radio" />
				</div>
				<div class="clear"></div>
				
				<?php $html->drawFormInput('entfernung_einsatzstelle', _('Entfernung zur E- Stelle (km)'), '', strtolower($_REQUEST['k']), array('class' => 'right small-text', 'bold-label' => true)) ?>
				<div class="clear"></div>
			</div>
			
			<div class="form-row">

			 	<p class="bold"><?php echo _('Fehlalarmierung') ?></p>
				<br />
				
				<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[fehlalarm_blind]" value="0" />		
				<?php $html->drawFormCheckbox('fehlalarm_blind', _('blinder Alarm'), 1, strtolower($_REQUEST['k']), array('class' => 'right fehlalarm radiocheck')) ?>
				<div class="clear"></div>
				
				<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[fehlalarm_boeswillig]" value="0" />
				<?php $html->drawFormCheckbox('fehlalarm_boeswillig', _('böswilliger Alarm'), 1, strtolower($_REQUEST['k']), array('class' => 'right fehlalarm radiocheck')) ?>
				<div class="clear"></div>
				
				<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[fehlalarm_fehler_gma]" value="0" />
				<?php $html->drawFormCheckbox('fehlalarm_fehler_gma', _('Fehlalarm GMA'), 1, strtolower($_REQUEST['k']), array('class' => 'right fehlalarm radiocheck')) ?>
				<div class="clear"></div>
				
				<?php $html->drawFormInput('fehlalarm_sonstige', _('Sonstige'), '', strtolower($_REQUEST['k']), array('class' => 'right')) ?>
				<div class="clear"></div>
				
			</div>
			
			<!--
			<div class="form-row">
				<?php $html->drawFormInput('personal_bereitstellung', _('In Bereitstellung (Anzahl)'), '', strtolower($_REQUEST['k']), array('class' => 'right small-text', 'bold-label' => true)) ?><div class="clear"></div>
			</div>
			-->
			
			<div class="form-row">
				<p class="left bold label content-grid-col3"><?php echo _('GMA vorhanden') ?>:</p>
				
				<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[gma_vorhanden]" value="0" />
				
				<div class="form_field radio_field left content-grid-col4">
					<label for="report_gma_vorhanden_ja"><?php echo _('Ja') ?>:</label>
					<input class="right" id="report_gma_vorhanden_ja" name="<?php echo strtolower($_REQUEST['k']) ?>[gma_vorhanden]" value="ja" type="radio" />
				</div>
				<div class="form_field radio_field right content-grid-col4">
					<label for="report_gma_vorhanden_nein"><?php echo _('Nein') ?>:</label>
					<input class="right" id="report_gma_vorhanden_nein" name="<?php echo strtolower($_REQUEST['k']) ?>[gma_vorhanden]" value="nein" type="radio" checked="checked" />
				</div>
				<div class="clear"></div>
			</div>
			
			<div class="form-row">
			
				<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[gma_ausgeloest]" value="0" />
			
				<div class="form_field radio_field left content-grid-col3">
					<label class="bold" for="report_gma_ausgeloest_ja"><?php echo _('GMA ausgelöst') ?>:</label>
					<input class="right" id="report_gma_ausgeloest_ja" name="<?php echo strtolower($_REQUEST['k']) ?>[gma_ausgeloest]" value="ja" type="radio" />
				</div>
				<div class="form_field radio_field right content-grid-col2">
					<label class="bold" for="report_gma_ausgeloest_nein"><?php echo _('GMA nicht ausgelöst') ?>:</label>
					<input class="right" id="report_gma_ausgeloest_nein" name="<?php echo strtolower($_REQUEST['k']) ?>[gma_ausgeloest]" value="nein" type="radio" />
				</div>
				<div class="clear"></div>
			</div>
			
			<div class="form-row">
				<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[gefahr_freisetzung_gef_stoffe]" value="0" />
				<?php $html->drawFormCheckbox('gefahr_freisetzung_gef_stoffe', _('Gefärd. durch Freisetzung von gefährlichen Stoffen'), 1, strtolower($_REQUEST['k']), array('class' => 'right', 'bold-label' => true)) ?><div class="clear"></div>
			</div>
			
			<div class="form-row" style="height:89px">&nbsp;</div>
			
		</div>
		
		<div class="content-grid-col2 report-content right">
			
			<div class="form-row">
			 	<?php $html->drawFormInput('einsatzobjekt', _('Einsatzobjekt'), $Einsatz->get('EINSATZ_STICHWORT'), strtolower($_REQUEST['k']), array('class' => 'right', 'bold-label' => true)) ?><div class="clear"></div>
				<?php $html->drawFormInput('einsatzobjekt_e-stelle', _('Einsatzstelle'), $Einsatz->get('EINSATZ_OBJEKTNAME'), strtolower($_REQUEST['k']), array('class' => 'right')) ?><div class="clear"></div>
				<?php $html->drawFormInput('einsatzobjekt_adresse', _('Adresse'), $Einsatz->get('EINSATZ_STRASSE1').' '.$Einsatz->get('EINSATZ_HNR'), strtolower($_REQUEST['k']), array('class' => 'right')) ?><div class="clear"></div>
				<?php $html->drawFormInput('einsatzobjekt_ort', _('Ort'), $Einsatz->get('EINSATZ_ORT').'/ '. $Einsatz->get('EINSATZ_ORTSTEIL'), strtolower($_REQUEST['k']), array('class' => 'right')) ?><div class="clear"></div>
			</div>
			
			<div class="form-row">
				<?php $html->drawFormInput('einsatzobjekt_eigentuemer', _('Eigentümer'), '', strtolower($_REQUEST['k']), array('class' => 'right', 'bold-label' => true)) ?><div class="clear"></div>
				<?php $html->drawFormInput('einsatzobjekt_eigentuemer_name', _('Name'), '', strtolower($_REQUEST['k']), array('class' => 'right')) ?><div class="clear"></div>
				<?php $html->drawFormInput('einsatzobjekt_eigentuemer_adresse', _('Anschrift'), '', strtolower($_REQUEST['k']), array('class' => 'right')) ?><div class="clear"></div>
				<br />
				<p class="right"><?php echo _('Mehrere Eigentümer im Feld "Einsatzbericht" erfassen!') ?></p>
				<div class="clear"></div>
			</div>
			<div class="form-row">
				<?php $html->drawFormInput('einsatzobjekt_geschaedigter', _('Geschädigter'), '', strtolower($_REQUEST['k']), array('class' => 'right', 'bold-label' => true)) ?><div class="clear"></div>
				<?php $html->drawFormInput('einsatzobjekt_geschaedigter_name', _('Name'), '', strtolower($_REQUEST['k']), array('class' => 'right')) ?><div class="clear"></div>
				<?php $html->drawFormInput('einsatzobjekt_geschaedigter_adresse', _('Anschrift'), '', strtolower($_REQUEST['k']), array('class' => 'right')) ?><div class="clear"></div>
				<br />
				<p class="right"><?php echo _('Mehrere Geschädigte im Feld "Einsatzbericht" erfassen!') ?></p>
				<div class="clear"></div>
			</div>
			
			<div class="form-row">
			 	<?php $html->drawFormInput('personen_rettung_anzahl_gesamt', _('Anzahl geretteter Personen'), '', strtolower($_REQUEST['k']), array('class' => 'right small-text readonly', 'bold-label' => true, 'readonly' => true)) ?><div class="clear"></div>
				<?php $html->drawFormInput('personen_rettung_anzahl_baulich', _('davon über baulichen Rettungsweg'), '', strtolower($_REQUEST['k']), array('class' => 'right small-text personen_rettung')) ?><div class="clear"></div>
				<?php $html->drawFormInput('personen_rettung_anzahl_hubrettung', _('davon über Hubrettungsfahrzeuge'), '', strtolower($_REQUEST['k']), array('class' => 'right small-text personen_rettung')) ?><div class="clear"></div>
				<?php $html->drawFormInput('personen_rettung_anzahl_tragbar', _('davon über tragbare Leitern'), '', strtolower($_REQUEST['k']), array('class' => 'right small-text personen_rettung')) ?><div class="clear"></div>
				<?php $html->drawFormInput('personen_rettung_anzahl_sonstiges', _('davon über Sonstiges'), '', strtolower($_REQUEST['k']), array('class' => 'right small-text personen_rettung')) ?><div class="clear"></div>
			</div>
			
			<div class="form-row">
				<?php $html->drawFormInput('tiere_rettung_anzahl_gesamt', _('Anzahl geretteter Tiere'), '', strtolower($_REQUEST['k']), array('class' => 'right small-text', 'bold-label' => true)) ?><div class="clear"></div>
			</div>
			
			<div class="form-row">
				<?php $html->drawFormInput('personal_schaeden_anzahl_gesamt', _('Anzahl geschädigter Feuerwehrangehöriger'), '', strtolower($_REQUEST['k']), array('class' => 'right small-text readonly', 'bold-label' => true, 'readonly' => true)) ?><div class="clear"></div>
				<?php $html->drawFormInput('personal_schaeden_anzahl_tod', _('tödlich verunglückte'), '', strtolower($_REQUEST['k']), array('class' => 'right small-text personal_schaeden')) ?><div class="clear"></div>
				<?php $html->drawFormInput('personal_schaeden_anzahl_verletzt', _('verletzte/ verunglückte'), '', strtolower($_REQUEST['k']), array('class' => 'right small-text personal_schaeden')) ?><div class="clear"></div>
			</div>
			
			<div class="form-row">
				<?php $html->drawFormInput('personen_schaeden_anzahl_gesamt', _('Anzahl geschädigter anderer Personen'), '', strtolower($_REQUEST['k']), array('class' => 'right small-text readonly', 'bold-label' => true, 'readonly' => true)) ?><div class="clear"></div>
				<?php $html->drawFormInput('personen_schaeden_anzahl_tod', _('tödlich verunglückte'), '', strtolower($_REQUEST['k']), array('class' => 'right small-text personen_schaeden')) ?><div class="clear"></div>
				<?php $html->drawFormInput('personen_schaeden_anzahl_verletzt', _('verletzte/ verunglückte'), '', strtolower($_REQUEST['k']), array('class' => 'right small-text personen_schaeden')) ?><div class="clear"></div>
			</div>
			
		</div>
		<div class="clear"></div>
		
		<div class="report-content">
			
			<div class="form-row">
				<p class="bold label"><?php echo _('Klassifikation des Hilfeleistungseinsatzes') ?></p>
				<br />
				
				<div class="left" style="width:50%">
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[klassifikation_menschen_in_notlage]" value="0" />
					<?php $html->drawFormCheckbox('klassifikation_menschen_in_notlage', _('Menschen in Notlage'), 1, strtolower($_REQUEST['k']), array('class' => 'right klassifikation radiocheck')) ?><div class="clear"></div>
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[klassifikation_gefahren_tiere_insekten]" value="0" />
					<?php $html->drawFormCheckbox('klassifikation_gefahren_tiere_insekten', _('Gefahren durch/ mit Tieren/ Insekten'), 1, strtolower($_REQUEST['k']), array('class' => 'right klassifikation radiocheck')) ?><div class="clear"></div>
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[klassifikation_betriebsunfall]" value="0" />
					<?php $html->drawFormCheckbox('klassifikation_betriebsunfall', _('Betriebsunfall'), 1, strtolower($_REQUEST['k']), array('class' => 'right klassifikation radiocheck')) ?><div class="clear"></div>
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[klassifikation_einsturz]" value="0" />
					<?php $html->drawFormCheckbox('klassifikation_einsturz', _('Einsturz baulicher Anlagen'), 1, strtolower($_REQUEST['k']), array('class' => 'right klassifikation radiocheck')) ?><div class="clear"></div>
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[klassifikation_amtshilfe_polizei]" value="0" />
					<?php $html->drawFormCheckbox('klassifikation_amtshilfe_polizei', _('Amtshilfe Polizei'), 1, strtolower($_REQUEST['k']), array('class' => 'right klassifikation radiocheck')) ?><div class="clear"></div>
				</div>
				<div class="right" style="width:45%">
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[klassifikation_verkehrsunfall_stoerung]" value="0" />
					<?php $html->drawFormCheckbox('klassifikation_verkehrsunfall_stoerung', _('Verkehrsunfälle- und störung'), 1, strtolower($_REQUEST['k']), array('class' => 'right klassifikation radiocheck')) ?><div class="clear"></div>
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[klassifikation_wasser_sturm]" value="0" />
					<?php $html->drawFormCheckbox('klassifikation_wasser_sturm', _('Wasser- und Sturmschaden'), 1, strtolower($_REQUEST['k']), array('class' => 'right klassifikation radiocheck')) ?><div class="clear"></div>
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[klassifikation_unterstuetzung_rettungsdienst]" value="0" />
					<?php $html->drawFormCheckbox('klassifikation_unterstuetzung_rettungsdienst', _('Unterstützung Rettungsdienst'), 1, strtolower($_REQUEST['k']), array('class' => 'right klassifikation radiocheck')) ?><div class="clear"></div>
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[klassifikation_gefaehrliche_stoffe]" value="0" />
					<?php $html->drawFormCheckbox('klassifikation_gefaehrliche_stoffe', _('Einsatz mit gefährlichen Stoffen u. Gütern'), 1, strtolower($_REQUEST['k']), array('class' => 'right klassifikation radiocheck')) ?><div class="clear"></div>
					<input type="hidden" name="<?php echo strtolower($_REQUEST['k']) ?>[klassifikation_oelspur]" value="0" />
					<?php $html->drawFormCheckbox('klassifikation_oelspur', _('Ölunfall/ Ölspur'), 1, strtolower($_REQUEST['k']), array('class' => 'right klassifikation radiocheck')) ?>
				</div>
				<div class="clear"></div>
			</div>
			
		</div>
		
		<div class="report-content">
			<div class="form-row">
				<?php $html->drawFormInput('klassifikation_sonstiger_einsatz', _('Sonstiger Einsatz'), '', strtolower($_REQUEST['k']), array('class' => 'right', 'style' => 'width:77%', 'bold-label' => true)) ?><div class="clear"></div>
			</div>
		</div>
		
		<div class="report-content">
			<div class="form-row">
				<?php $html->drawFormTextarea('eingesetzte_geraete', _('Eingesetzte Geräte'), '', strtolower($_REQUEST['k']), array('class' => 'right', 'rows' => '5', 'bold-label' => true)) ?><div class="clear"></div>
			</div>
		</div>
		
		<div class="report-content">
			<div class="form-row">
				<?php $html->drawFormTextarea('verbrauchsmaterial', _('Verbrauchsmaterial'), '', strtolower($_REQUEST['k']), array('class' => 'right', 'rows' => '5', 'bold-label' => true)) ?><div class="clear"></div>
			</div>
		</div>
		
	</div>
	
	<!-- Seite 2 als eigenes Template einbinden -->
		<?php include VIEW_PATH.'/Report/hilfeleistung2.phtml' ?>
	<!-- Seite 2 als eigenes Template einbinden -->
	
	<?php echo $html->drawFormEnde() ?>
	
	<script type="text/javascript">
	//<![CDATA[
	
		$(document).ready(function(){

			initDatePicker();

			// Validierung des Datums (muss in der Vergangeheit liegen)
			$('.datepicker').on('change', function() {
				
				var arrDate = $(this).val().split('.');
				var objDate = new Date(arrDate[1] + '/' + arrDate[0] + '/'+arrDate[2]);
				var objToday = new Date();

				// Zeiten des Datums auf null setzen
				objToday.setHours(0); objToday.setMinutes(0); objToday.setSeconds(0); objToday.setMilliseconds(0);

				if (objDate <= objToday)
				{
					// nichts tun... Datum wird übernommen
					return;
				}
				else
				{
					alert('Datum muss in der Vergangenheit liegen!');

					// Datum auf "heute" stetzen 
					$(this).datepicker('setDate', new Date());
					$(this).datepicker().close();
				}

			});

			// Formular absenden
			$('#report-submit-save').click(function(){ $('.report-save-form').submit() });

			// Umschalten der Seiten Tabs
			$('.switch-tab').bind('click', function(){

				if (!$(this).hasClass('active'))
				{

					var eID = $(this).children('span').attr('class');

					$('.switch-tab').removeClass('active');
					$('.report-content-wrap').hide();

					$('#' + eID).show();
					$(this).addClass('active');
					
				}

				return false;
				
			})

			// hinzufügen weiterer Fahrzeuge 
			$('.add-resource').click(function(){

				var strHTML 	= $('table.resourcen-overview tbody').html();
				var intIndex 	= parseInt($(this).attr('id').replace('add_index_', ''));
				var addHTML 	= $('.table-add-report-resource tbody').html();

				// neuen HTML Inhalt "zusammenbauen" und einsetzen
				addHTML = addHTML.replace(/###index###/g, $(this).attr('id').replace('add_index_', ''));
				$('table.resourcen-overview tbody').html(strHTML + addHTML);

				// Index hochzählen
				intIndex = intIndex + 1;
				$(this).attr('id', 'add_index_' + intIndex);

				initDatePicker();

				return false;
				
			})

			// hinzufügen Personal 
			$('.add-personal').click(function(){

				var strHTML 	= $('table.personal-overview tbody').html();
				var intIndex 	= parseInt($(this).attr('id').replace('add_index_', ''));
				var addHTML 	= $('.table-add-report-personal tbody').html();

				// neuen HTML Inhalt "zusammenbauen" und einsetzen
				addHTML = addHTML.replace(/###index###/g, $(this).attr('id').replace('add_index_', ''));
				$('table.personal-overview tbody').html(strHTML + addHTML);

				// Index hochzählen
				intIndex = intIndex + 1;
				$(this).attr('id', 'add_index_' + intIndex);

				$('.calc-personal').bind('change', function(){
					calcPersonal();
				})

				return false;
				
			})

			calcActionTime(); // setzt die Einsatzzeit beim laden des Einsatzes

			// ruft die Funktionen beim ändern der Felder erneut auf
			$('.calc-aus').bind('change', function(){
				calcAusgerueckt();
			})

			$('.calc-personal').bind('change', function(){
				calcPersonal();
				calcActionTime();
			})

			// ruft die Funktionen beim ändern der Felder erneut auf
			$('.personen_rettung').bind('change', function(){
				calcRettungAnzahl();
			})
			
			// ruft die Funktionen beim ändern der Felder erneut auf
			$('.personal_schaeden').bind('change', function(){
				calcAnzahlPersonalSchaeden();
			})

			// ruft die Funktionen beim ändern der Felder erneut auf
			$('.personen_schaeden').bind('change', function(){
				calcAnzahlPersonenSchaeden();
			})

			// verleiht den checkboxen die Funktionalität eines Radiobuttons
			$('.radiocheck').bind('click', function(){

				var arr_eID = $(this).attr('id').split('_');

				if (arr_eID[1] == 'brandumfang' || arr_eID[1] == 'fehlalarm')	
				{
					// sonderbehandlung Brandumfang u. Fehlalarm
					$('.brandumfang').prop('checked', false);
					$('.fehlalarm').prop('checked', false);
				}
				else
				{
					$('.' + arr_eID[1]).prop('checked', false);
				}
				$(this).prop('checked', true);

			})	

			
		}) // $(document).ready(function()

		function initDatePicker()
		{

			// Datepicker Settings
			$('.datepicker').datepicker({
				dayNamesShort: ['So','Mo','Di','Mi','Do','Fr','Sa'],
		        dayNamesMin: ['So','Mo','Di','Mi','Do','Fr','Sa'],
		        firstDay: 1,
				dateFormat: "dd.mm.yy",
			});
			
		}
		
		// function zum entfernen der dynamischen Zeilen bei der Resourcenübersicht
		function remResource(oEL)
		{
			var strID = $(oEL).attr('id').replace('rem-resource-', '');

			$('#add-resource-' + strID).remove();

			return false;
		}

		// function zum entfernen der dynamischen Zeilen bei der Personalübersicht
		function remPersonal(oEL)
		{
			var strID = $(oEL).attr('id').replace('rem-personal-', '');

			$('#add-personal-' + strID).remove();

			calcPersonal();

			return false;
		}

		// berechnet die Gesamteinsatzzeit
		function calcActionTime()
		{

			var min = 0;
			var day = 0;
			var std = 0;
			var gesMin = 0;
			var gesStd = 0;
			var multiplikator = 0;
			
			$(document).find('input.einsatzzeit-min').each(function(index){

				multiplikator = 0;
				
				if (parseInt($('#reportpersonal'+ index +'_eingesetzt_hoeherer').val()) > 0)
					multiplikator = Number(multiplikator) + parseInt($('#reportpersonal'+ index +'_eingesetzt_hoeherer').val());

				if (parseInt($('#reportpersonal'+ index +'_eingesetzt_gehobener').val()) > 0)
					multiplikator = Number(multiplikator) + parseInt($('#reportpersonal'+ index +'_eingesetzt_gehobener').val());

				if (parseInt($('#reportpersonal'+ index +'_eingesetzt_mittlerer').val()) > 0)
					multiplikator = Number(multiplikator) + parseInt($('#reportpersonal'+ index +'_eingesetzt_mittlerer').val());

				if (parseInt($('#reportpersonal'+ index +'_eingesetzt_ff').val()) > 0)
					multiplikator = Number(multiplikator) + parseInt($('#reportpersonal'+ index +'_eingesetzt_ff').val());
				
				if (parseInt($(this).val()) > 0) min = Number(min) + (parseInt($(this).val()) * multiplikator);
			})
			
			$(document).find('input.einsatzzeit-day').each(function(index){

				multiplikator = 0;

				if (parseInt($('#reportpersonal'+ index +'_eingesetzt_hoeherer').val()) > 0)
					multiplikator = Number(multiplikator) + parseInt($('#reportpersonal'+ index +'_eingesetzt_hoeherer').val());

				if (parseInt($('#reportpersonal'+ index +'_eingesetzt_gehobener').val()) > 0)
					multiplikator = Number(multiplikator) + parseInt($('#reportpersonal'+ index +'_eingesetzt_gehobener').val());

				if (parseInt($('#reportpersonal'+ index +'_eingesetzt_mittlerer').val()) > 0)
					multiplikator = Number(multiplikator) + parseInt($('#reportpersonal'+ index +'_eingesetzt_mittlerer').val());

				if (parseInt($('#reportpersonal'+ index +'_eingesetzt_ff').val()) > 0)
					multiplikator = Number(multiplikator) + parseInt($('#reportpersonal'+ index +'_eingesetzt_ff').val());
				
				if (parseInt($(this).val()) > 0) day = Number(day) + (parseInt($(this).val()) * multiplikator);
			})

			$(document).find('input.einsatzzeit-std').each(function(index){

				multiplikator = 0;

				if (parseInt($('#reportpersonal'+ index +'_eingesetzt_hoeherer').val()) > 0)
					multiplikator = Number(multiplikator) + parseInt($('#reportpersonal'+ index +'_eingesetzt_hoeherer').val());

				if (parseInt($('#reportpersonal'+ index +'_eingesetzt_gehobener').val()) > 0)
					multiplikator = Number(multiplikator) + parseInt($('#reportpersonal'+ index +'_eingesetzt_gehobener').val());

				if (parseInt($('#reportpersonal'+ index +'_eingesetzt_mittlerer').val()) > 0)
					multiplikator = Number(multiplikator) + parseInt($('#reportpersonal'+ index +'_eingesetzt_mittlerer').val());

				if (parseInt($('#reportpersonal'+ index +'_eingesetzt_ff').val()) > 0)
					multiplikator = Number(multiplikator) + parseInt($('#reportpersonal'+ index +'_eingesetzt_ff').val());
				
				if (parseInt($(this).val()) > 0) std = Number(std) + (parseInt($(this).val()) * multiplikator);
			})

			gesMin = parseInt(day * 1440) + parseInt(std * 60) + parseInt(min);

			gesStd = Math.round((gesMin / 60) * 100) / 100;

			// formatieren der Gesamtzeit
			gesStd = gesStd.toString().replace('.', ',');

			$('#report_zeit_eingesetzt').val(gesStd); // Formularfeld füllen

			return false;
		}

		// berechnet die ausgerückte Personalstärke
		function calcAusgerueckt()
		{
			var pers = 0;

			$(document).find('input.calc-aus').each(function(){
				if (parseInt($(this).val()) > 0) pers = Number(pers) + parseInt($(this).val());
			})
			
			$('#report_anzahl_ausgerueckt').val(pers); // Formularfeld füllen
			
			return false;
		}

		// berechnet die Personalstärke gesamt
		function calcPersonal()
		{
			var pers = 0;
			
			$(document).find('input.calc-personal').each(function(){
				if (parseInt($(this).val()) > 0) pers = Number(pers) + parseInt($(this).val());
			})
			
			$('#report_anzahl_eingesetzt').val(pers); // Formularfeld füllen
			
			return false;
		}

		// "Verständigung/ Abwesenheit" immer nur eine Auswahl erlauben -> "radio"
		function checked_value(oEL)
		{
			var arrClasses = $(oEL).attr('class').split(' ');
			var strClass = arrClasses[0];

			if ($(oEL).prop('checked'))
			{
				$('.' + strClass).prop('checked', false);
				$(oEL).prop('checked', true);
			}
			else
			{
				$(oEL).prop('checked', false);
			}
		}	

		// berechnet die Anzahl der geretteten Personen
		function calcRettungAnzahl()
		{
			var sum = 0;
			$(document).find('input.personen_rettung').each(function(){
				if (parseInt($(this).val()) > 0) sum = Number(sum) + parseInt($(this).val());
			})

			$('#report_personen_rettung_anzahl_gesamt').val(sum); // Formularfeld füllen

			return false; 
		}

		// berechnet die Anzahl der geretteten Personen
		function calcAnzahlPersonenSchaeden()
		{
			var sum = 0;
			$(document).find('input.personen_schaeden').each(function(){
				if (parseInt($(this).val()) > 0) sum = Number(sum) + parseInt($(this).val());
			})

			$('#report_personen_schaeden_anzahl_gesamt').val(sum); // Formularfeld füllen

			return false; 
		}

		// berechnet die Anzahl der geretteten Personen
		function calcAnzahlPersonalSchaeden()
		{
			var sum = 0;
			$(document).find('input.personal_schaeden').each(function(){
				if (parseInt($(this).val()) > 0) sum = Number(sum) + parseInt($(this).val());
			})

			$('#report_personal_schaeden_anzahl_gesamt').val(sum); // Formularfeld füllen

			return false; 
		}
		
	
	//]]>
	</script>
	
</div>