<?php 
/**
 * Profildaten ändern
 */
?>
<div id="user-profil-edit" class="content-form">

	<h2><span class="fa fa-user"></span>&nbsp;<?php echo _('Profildaten') ?> [<i><?php echo $this->view['data']->get('username') ?></i>]</h2>
	
	<?php echo $this->drawMessages(); ?>
	
	<p><?php echo _('Profil bearbeiten, Felder mit * sind Pflichtangaben.') ?></p>
	
	<?php $html = Html_Factory::getHtml('forms') ?>
	<?php echo $html->drawFormStart('post', $this->tools->buildUrl('User', 'save', array('uid' => $this->view['data']->get('id'), 'cmd' => 'profil')), '', array()) ?>
		<?php $html->drawFormInput('name', _('Name'), $this->view['data']->get('name'), '', array()) ?>
		<?php $html->drawFormInput('vorname', _('Vorame'), $this->view['data']->get('vorname'), '', array()) ?>
		<?php $html->drawFormInput('email', _('E- Mail'), $this->view['data']->get('email'), '', array('class' => 'required')) ?>
		<?php $html->drawFormInput('username', _('Benutzername * '), $this->view['data']->get('username'), '', array('class' => 'required', 'disabled' => true)) ?>
		<span class="field-info"><?php echo _('Zum ändern des Passwortes müssen beide Felder richtig ausgefüllt sein') ?></span>
		<?php $html->drawFormPasswd('passwd1', _('neues Passwort * '), '', array('class' => 'required')) ?>
		<?php $html->drawFormPasswd('passwd2', _('wiederholen * '), '', array('class' => 'required')) ?>
		<div class="left"><?php $html->drawFormSubmit('submit_save', _('Profil Speichern'), '', array('class' => 'submit button')) ?></div>
		<div class="clear"></div>
	<?php echo $html->drawFormEnde() ?>
	
</div>